Add Openstack Component Description
openstack-kr/contributhon-2020 pull request #78
Opened 2020-09-09 15:21 UTC by lkeonwoo94

## WHY (PR을 제출하는 이유)

OSS Openstack team 첫번째 meeting 내용 기록

## HOW (PR을 통해 어떤 부분을 수정하고자 하는가)

Openstack Component에 대한 설명을 기록한 문서를 추가하고자 한다

## Related Issues

none

## Checklist (확인 사항)

- [x] I signed the CLA. (라이선스 동의 여부 - Apache License를 따릅니다)
- [ ] I listed the related issues. (관련 이슈를 제시하여 연결하였습니다)
- [x] I am willing to follow-up on review comments in a timely manner. (리뷰 내용을 잘 따르고자 합니다)

2020-09-09 15:45 UTC, lkeonwoo94 commented
![image](https://user-images.githubusercontent.com/32762192/92621482-d3f6c000-f2fe-11ea-8e87-58ea6fa50d79.png)

Local tox에서는 Build가 되었는데 어느부분이 잘못되었을까요? ㅠㅠ ...

Details에서는 아래와 같이 보입니다.

build succeeded.
12:42:58 AM: The HTML pages are in doc/build/html.
12:42:58 AM: ___________________________________ summary ____________________________________
12:42:58 AM: ERROR:   lint: commands failed
12:42:58 AM:   docs: commands succeeded
12:42:58 AM: ​
12:42:58 AM: ┌─────────────────────────────┐
12:42:58 AM: │   "build.command" failed    │
12:42:59 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
12:42:58 AM: └─────────────────────────────┘
12:42:58 AM: ​
12:42:58 AM:   Error message
12:42:58 AM:   Command failed with exit code 1: tox
12:42:58 AM: ​
12:42:58 AM:   Error location
12:42:58 AM:   In Build command from Netlify app:
12:42:58 AM:   tox
12:42:58 AM: ​

2020-09-09 16:20 UTC, lkeonwoo94 commented
indent 문제인 것 같습니다. 수정후 재 check 하겠습니다

2020-09-09 16:26 UTC, lkeonwoo94 commented
indent 문제인것 같습니다. 수정 후 재 commit 하겠습니다.

2020-09-10 13:39 UTC, ppiyakk2 commented
@lkeonwoo94 혹시 지금 계속 수정하는 내용이 로컬에서 tox -e docs 로는 검출이 안되나요?

2020-09-10 15:16 UTC, ppiyakk2 commented on doc/source/keonwoo_lee/index.rst
>  - stackanalytics pr : stackalytics/default_data#213
이 PR도 하이퍼링크로 만들어주세요

2020-09-10 15:16 UTC, ppiyakk2 requested changes
코멘트 확인 부탁드립니다.

2020-09-10 15:19 UTC, lkeonwoo94 commented
> @lkeonwoo94 혹시 지금 계속 수정하는 내용이 로컬에서 tox -e docs 로는 검출이 안되나요?

넵. 로컬 tox 에서는 indent 문제를 잡지 못하고 있습니다 ㅠㅠ

2020-09-10 15:20 UTC, lkeonwoo94 commented
> 코멘트 확인 부탁드립니다.

넵 확인했습니다 바로 반영하겠습니다

2020-09-10 15:21 UTC, lkeonwoo94 commented on doc/source/keonwoo_lee/index.rst
>  - stackanalytics pr : stackalytics/default_data#213
넵 알겠습니다 ! ~

2020-09-10 15:24 UTC, lkeonwoo94 commented on doc/source/keonwoo_lee/index.rst
>  - stackanalytics pr : stackalytics/default_data#213
넵 바로 반영하겠습니다

2020-09-10 15:32 UTC, ppiyakk2 approved these changes
Okay!!! Let's merge it!!!!!!!!!!!!

2020-09-10 15:32 UTC, merged

2020-09-10 15:34 UTC, lkeonwoo94 commented
> Okay!!! Let's merge it!!!!!!!!!!!!

감사합니다 ~~!! ㅎㅎㅎㅎ