add launchpad and zanata id to index.rst
openstack-kr/contributhon-2020 pull request #82
Opened 2020-09-11 12:23 UTC by vdqvdw

## WHY (PR을 제출하는 이유)

openstack launchpad와 zanata id를 index.rst에 추가하려고 합니다.

## HOW (PR을 통해 어떤 부분을 수정하고자 하는가)

index.rst 파일을 수정합니다.

## Related Issues

## Checklist (확인 사항)

Checking the relevant checkboxes (`[x]`) will ensure a smooth and quick review process. (아래 부분을 체크해주시면 리뷰하는데 더 좋습니다)

- [x] I signed the CLA. (라이선스 동의 여부 - Apache License를 따릅니다)
- [x] I listed the related issues. (관련 이슈를 제시하여 연결하였습니다)
- [x] I am willing to follow-up on review comments in a timely manner. (리뷰 내용을 잘 따르고자 합니다)

2020-09-11 13:36 UTC, ppiyakk2 requested changes
댓글 확인 부탁드립니다.

2020-09-11 13:36 UTC, ppiyakk2 commented on doc/source/kyungyong_choi/index.rst
> +- zanata id : `choikyungyong <https://translate.openstack.org/profile/view/choikyungyong?dswid=2091>`_
stackanalytics 에 PR은 안보내신건가요?

2020-09-11 13:36 UTC, ppiyakk2 commented on doc/source/kyungyong_choi/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
이 파일은 불필요한 파일인데 삭제해주세요

2020-09-12 07:15 UTC, vdqvdw commented on doc/source/kyungyong_choi/index.rst
> +- zanata id : `choikyungyong <https://translate.openstack.org/profile/view/choikyungyong?dswid=2091>`_
보냈는데, 그쪽도 에러가 나서 해결중입니다.

2020-09-12 07:15 UTC, vdqvdw commented on doc/source/kyungyong_choi/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
넵

2020-09-12 08:26 UTC, vdqvdw commented on doc/source/kyungyong_choi/index.rst
> +- zanata id : `choikyungyong <https://translate.openstack.org/profile/view/choikyungyong?dswid=2091>`_
에러 해결하고 merge 기다리고 있습니다.

https://github.com/openstack-kr/contributhon-2020/issues/86

2020-09-13 12:37 UTC, ppiyakk2 approved these changes

2020-09-13 12:37 UTC, merged